src/components/auction/OrderbookWidget/index.tsx
closes #283
I tried out different values and actually, I like it better if the line does not go until the end of the chart.
Here is one of the auction that was previously not nicely displayed: 
If we wanna display the green line until the end, all we need to change is: 
```
// Reduce the min in a 5%
priceAxis.min = min - min * 0.05
```
=> Adding additional point to display the orderbook until the end

src/components/auction/Charts/XYChart.ts, src/components/auction/OrderbookChart/index.tsx, src/components/auction/OrderbookWidget/index.tsx, src/hooks/useChart.ts
Closes #301 
Also:
closes #228 (see last comment here)
closes #224 
closes #258 
closes #217 
I removed the gridlines added manually, because breaks the chart in some cases
Look like this ...
=> Chart bug - The orange order, the new one is no longer shown

src/components/modals/TransactionsModal/index.tsx, src/hooks/useApproveCallback.ts, src/state/transactions/actions.ts, src/state/transactions/hooks.tsx, src/state/transactions/reducer.ts
Closes #369 
This is an idea taken from the original repository, seems like when a stuck tx is found `useHasPendingApproval` returns true (this also returns false when the amount is not specified), I'm not completely sure that this was the problem in mainnet but being more common to have stuck tx in mainnet I would give a try to this approach.
=> Make search of pending more specific

src/components/auction/OrderbookWidget/index.tsx
closes #404 
The issue was that the clearing price displayed a value of 0. Something that should never happen. Fixed price calculation.
=> tiny fix in price calcuation function

src/components/auctions/AuctionInfoCard/index.tsx
closes #395
Tiny fix. Shows actual price instead of min price on the featured auction card.
=> Showing price instead of min price

src/state/application/updater.ts
I think it is fine, we keep infura asking for new blocks, once a user is connected FOR NOW. 
Later on, we can refactor it cleaner
closes #401
Basically, this PR prevents the block number updates and all related actions, as long as no users is connected
=> Eliminates infura calls, if no account is available

src/components/auction/Charts/XYChart.ts
When our customerr was running the auction, they would get:
https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=14&chainId=4#topAnchor
and it looked like only 2k volume was placed. But indeed 20k was placed
Now its fixed
=> fixing chart for boson auction

src/components/auction/AuctionDetails/index.tsx, src/components/auctions/AllAuctions/index.tsx, src/components/auctions/AuctionInfoCard/index.tsx, src/components/auctions/FeaturedAuctions/index.tsx, src/components/navigation/Mainmenu/index.tsx, src/components/navigation/Mobilemenu/index.tsx, src/components/navigation/sections.tsx
Closes #415 
Closes #419
There's still room for improvement, but this should look better than before.
- #419 should be fixed.
- _Auction details may look ugly (...)_ -> Info should look better now.
- _Auction details exceed grid width (...)_ -> Should be fixed.
-  _Impossible to tap on a tooltip (...)_ -> There's not much we can do about this, we probably need to think some other solution for mobile.
- _Chart is too small on iPhone 12 mini (...)_ -> Not really a lot we can do here (especially without an iPhone 12 mini available). It looks fine in the several devices I used, though.
- _It would be nice to add a 'Back' button (...)_ -> No, that would be a nightmare. They can use the browser's back button, or the navigation menu.
- _Timing on a featured widget looks ugly when screen width < …
=> (Fix) Responsive issues

package.json, src/components/common/UserDropdown/index.tsx, src/components/modals/common/WalletConnectData/index.tsx, src/constants/index.ts, src/hooks/index.ts
So the problem was that the `useEagerConnect` hook only checks if there's an existing metamask connection, it doesn't check walletconnect. 
This PR:
- Add walletconnect check to useEagerConnect
- Increase supported node versions in package.json
=> Bug: Walletconnect disconnects after page reload

src/components/auction/OrderbookWidget/index.tsx
closes #421 
please check thte `auctionId=14&chainId=4#topAnchor` and the live boson auction as a review/
logic change:
set the most right  bid element really at the max displayed price and not the previous max_value
=> fixes the U shape in the chart

src/components/auction/AuctionDetails/index.tsx
Closes #461 
I moved the tokens' logos to the right so it's easier to put the numbers on top when on mobile.
=> (fix) token logo on mobile

src/components/auction/Claimer/index.tsx, src/components/auction/OrderPlacement/index.tsx, src/components/auction/OrderbookChart/index.tsx, src/components/pureStyledComponents/EmptyContent.tsx
Closes #463
(1) Should be fixed.
(2) I suspect it was a temporary issue (can't be sure, sorry).
(3) I asked a friend who owns an iPhone 8 and it has the same issue with the chart's height. I created an issue here https://github.com/gnosis/ido-ux/issues/464 to try to fix that.
=> (Fix) Mobile issues

src/components/auction/OrderPlacement/index.tsx, src/state/orderPlacement/hooks.ts
Users were placing orders bleow the clearing price, although this makes no sense and they are just wasting gas.
Hence, in the no-order-cancelation phase, we don't allow placing orders below the current clearing price, as the clearing price can only increase.
can be easily tested on auction: `auction?auctionId=33&chainId=4#topAnchor`
=> Does not allow to place orders below the clearing price

src/components/auction/Claimer/index.tsx, src/components/auction/OrderPlacement/index.tsx, src/hooks/useClaimOrderCallback.ts, src/state/orderPlacement/hooks.ts
Closes #359 
This should work better now.
In the future we should modify the "Error" logic to make it capable of dealing with different status returned by the hooks.
We should be able to discern if we are dealing with an actual error, or if we are dealing with a "Success" status (ie: "You already claimed your funds" is an OK status and it should display a green checkmark, and not the red warning icon).
=> (Fix) Waiting modal appears when clicking on the Claim button again

src/components/auction/OrdersTable/index.tsx, src/hooks/useCancelOrderCallback.ts, src/state/orders/actions.ts, src/state/orders/hooks.ts, src/state/orders/reducer.ts, src/state/transactions/updater.tsx
Closes #260 
Added a status of `PENDING_CANCELLATION`
When an order is cancelled, disappeared immediately using the action [`RemoveOrders`](https://github.com/gnosis/ido-ux/blob/fec72ef5156b4dafb6ecfc5c70945ab4a6a19629/src/state/orders/actions.ts#L13) .
Adding a new status [can be set individually](https://github.com/henrypalacios/ido-ux/blob/ad51de32c7cf51c11b041425360909cd9528200e/src/state/orders/reducer.ts#L51), and after confirmation [it will be removed](https://github.com/henrypalacios/ido-ux/blob/ad51de32c7cf51c11b041425360909cd9528200e/src/state/transactions/updater.tsx#L54).
I have also disabled the cancel button once it has been pressed.
Issue: [260](https://github.com/gnosis/ido-ux/issues/260)
_auctionId_: 17
_chainId_: 4
=> Add PENDING_CANCELLATION state #260

src/components/auction/AuctionDetails/index.tsx, src/components/auction/OrdersTable/index.tsx, src/pages/Auction/index.tsx
This fixes somehow the issue:
https://github.com/henrypalacios/ido-ux/issues/2
By shifting the logic for the price invention into a lower-level component, we are saving some rerendering. This rerendering previously also always triggered  the new API call to get the user orders, as the actionidentifier was a new object, and hence it would reload the orders without the not yet mined order.
=> fix for order deletion during order placmeent

src/components/auction/Claimer/index.tsx
Since the contracts can not pay out xdai, we should always show to claim wxdai
Eg. test on auction auction?auctionId=21&chainId=100#topAnchor
=> Always claim wxdai, instead of xdai

src/components/layout/Header/index.tsx, src/components/modals/WalletModal/index.tsx, src/ethereum.d.ts, src/utils/setupNetwork.ts
closes #513
Since metamask does not yet implement the [switching functionality](https://github.com/ethereum/EIPs/pull/3326), this PR only implements the adding network functionality and with it comes automatically the switching network to xdai functionality.
Try it out:
- have metamask locked
- visit the website
- choose an xdai auction
- click connect
=> adds metamask addWalletFunctionality

src/components/auction/Claimer/index.tsx, src/components/auction/OrderPlacement/index.tsx
I'm not completely sure about what's needed here, but hopefully this is OK. It's obviously still missing some logic, which I think @josojo will implement.
It should look more or less like these:
We could create a better workflow for this later, maybe similar to what we implemented on https://github.com/gnosis/conditional-tokens-explorer for Wrapping / Unwrapping (which looks or looked like these other images)
=> (add) wrap / unwrap buttons

src/components/auction/OrderPlacement/index.tsx, src/components/modals/common/PlaceOrderModalFooter/index.tsx, tsconfig.json
closes: #469 
Added **verification** when the placement price is _below_ the **cleatingPrice**.
After pressing "Place Order" if the the `auctionSTate` is `ORDER_PLACING_AND_CANCELING` and the price is __below__ the `clearingPrice` This allows a **warning message** to be displayed to the user.
⚠️ In doing so, I came across this with this [issue](https://github.com/gnosis/ido-ux/issues/548).
**Enviroment:**
auctionId: 69
chainId: 4
=> Add warn risk not covering Clearing Price

src/state/orderPlacement/hooks.ts, src/types.d.ts
closes: #507 
When auction `orderCancellationtime` expires, The `auctionState` is not updated so the "cancel" **button remains enable**.
Update a `useEffect` that updates the `auctionState` when the `endTime` expires
⚠️ it seems questionable to me whether to use an **action** through redux, if this event needs to be heard in another component.
- Enviroment
auctionId: 20
chainId: 4
=> Add update AuctionState after order cancellation time expires

src/api/AdditionalServicesApi.ts
Currently, the auctions are not loaded in dev in case one API is rebooting and then everything is blocked. This PR fixes it
=> Don't throw if api is not available

src/components/auction/Claimer/index.tsx, src/hooks/useClaimOrderCallback.ts, src/state/transactions/hooks.tsx
closes: #560 
Added `ClaimState`, specifically PENDING status after claim txs.
**Problem:** 
after claiming an auction the user can press the **claim button again**, without waiting for the transaction to be mined.
**Proposal:**
Add transaction detail [in the summary](https://github.com/gnosis/ido-ux/blob/8d0f81033341b12c7d6d7603889033590288a2b1/src/state/transactions/hooks.tsx#L147) to identify **recent unconfirmed transactions** 
⚠️ this solution will not work if i open the auction from another client
**Enviroment:**
ChainId: 4
AuctionId: 89, 90
=> Add PENDING ClaimState after claiming

src/components/modals/WalletModal/index.tsx
closes: #598
Fix Header Text in `WalletModal`.
Problem:
=> Fix Wrong header on WalletModal

src/components/auction/OrderPlacement/index.tsx, src/components/form/PriceInputPanel/index.tsx
I realized that it's better to depend on the chainID from URL instead of the web3 session, in order to always show the correct tokenSymbol
=> tokenDisplay depending on chainId from url

src/constants/tokens/rinkeby.ts
Closes #698 
This needs to make a change in `ido-contracts`, the change is:
```diff
diff --git a/assets/tokens/rinkeby-token-list.json b/assets/tokens/rinkeby-token-list.json
index 73b89b6..87df10d 100644
--- a/assets/tokens/rinkeby-token-list.json
+++ b/assets/tokens/rinkeby-token-list.json
@@ -5,12 +5,7 @@
"minor": 0,
"patch": 1
},
-  "keywords": [
-    "IDO",
-    "Rinkeby",
-    "tokens",
-    "trusted"
-  ],
+  "keywords": ["IDO", "Rinkeby", "tokens", "trusted"],
"logoURI": "https://avatars.githubusercontent.com/u/24954468?s=200&v=4",
"timestamp": "2021-03-17T14:25:00.000Z",
"tokens": [
@@ -189,6 +184,14 @@
"decimals": 18,
"address": "0x67BF1BB0b98FCbBC0EE3ffbE7669acC3e9E44FdF",
"logoURI": "https://i.ibb.co/By0VbLK/stakehouse-dp.png"
+    },
+    {
+      "name": "VITA",
+ …
```
=> Add Token to rinkeby list

src/components/auction/AuctionDetails/index.tsx
@elena-zh this should tackle your comment on the PR of minFunding PR #738 738
Testplan:
http://localhost:3000/auction?auctionId=17&chainId=4#topAnchor no longer breaks
=> hotfix div by 0

src/components/modals/WalletModal/index.tsx, src/components/modals/common/PendingView/index.tsx
closes: #658 
When I connect via `walletconnect` from a network not supported by the specified the app is crash.
=> Handling app crashing when walletconnect is using another supported network

src/assets/links/kycLinks.json, src/components/auction/OrderPlacement/index.tsx, tsconfig.strict.json
This adds the kyc link that can be maintained for each auctioning token
the KYC json list should be fetched from this github repo, instead of the build, but for reviewing the PR I am pulling it via internal reference.
If the account is not yet connected, currently the interface shows that the user is not allowlisted, which is confusing. I changed that behaviour as well and show the user the connect button.
@henrypalacios any proposal for improvements are highly welcome
=> adding kyc link and  connect button
