gnosis/ido-ux

src/pages/Licenses/index.tsx

(add) license

---

src/api/TokenLogosServiceApi.ts

We actually don't need the token symbol so for now, We can just live with the coingecko error.

[issue-375] Coingecko token list failed validation

---

src/components/auction/OrderPlacement/index.tsx
src/hooks/usePlaceOrderCallback.ts

The current dev branch has only an ugly solution, which I implemented during the boson call. I think this is the right way to display the auction symbol only at the right time.

Display locked symbol only when needed

---

src/pages/Privacy/index.tsx

(fix) privacy policy typo

---

src/api/AdditionalServicesApi.ts

[issue-357] showing site, if only 1 endpoint is up

---

src/components/auction/Charts/XYChart.ts

Added prefixes for big numbers.

[issue-336] Long numbers on the chart overlap

---

public/index.html
src/components/auction/AuctionBody/index.tsx
src/components/auction/AuctionDetails/index.tsx
src/components/auction/OrderPlacement/index.tsx
src/components/auction/OrdersTable/index.tsx
src/components/auctions/AllAuctions/index.tsx
src/components/auctions/FeaturedAuctions/index.tsx
src/components/buttons/ButtonMenu/index.tsx
src/components/common/CookiesBanner/index.tsx
src/components/common/Transaction/index.tsx
src/components/common/UserDropdown/index.tsx
src/components/icons/MenuIcon.tsx
src/components/layout/Footer/index.tsx
src/components/layout/Header/index.tsx
src/components/modals/WalletModal/index.tsx
src/components/modals/common/PlaceOrderModalFooter/index.tsx
src/components/navigation/Mobilemenu/index.tsx
src/components/pureStyledComponents/Cell.tsx
src/pages/Auction/index.tsx
src/pages/Documentation/index.tsx
src/pages/Landing/index.tsx
src/pages/Overview/index.tsx

Closes #55 
Closes #75
Closes #380 
OK, this is not perfect but it'll work (I think).
Tested it on a desktop browser's responsive view emulation, and also using Opera Mobile (which features a crypto wallet) on my cellphone.
I could use the app, and it looks OK.
I couldn't use the Confirm button when trying to place an order, though. The confirmation window just closes... and nothing happens. Maybe it's a browser / wallet problem? I had no other issues but this one.
Also, I'm not sure about wallet connecting / disconnecting on mobile. From what I understand you can't "connect" to the wallet on the browser, you just accept to use it (so disconnecting would make no sense, but I don't know).
Anyways: it "works", and we can probably merge this and fix any issues later.

(Feature) Responsive views

---

src/components/modals/common/PlaceOrderModalFooter/index.tsx

Displaying correct min buy

---

src/components/auction/Charts/XYChart.ts
src/components/auction/OrderPlacement/index.tsx
src/components/auction/OrdersTable/index.tsx
src/components/auctions/FeaturedAuctions/index.tsx
src/components/modals/ConfirmationModal/index.tsx
src/components/modals/common/CancelModalFooter/index.tsx
src/hooks/useCancelOrderCallback.ts

(Fix) Remove cancelation date when there are no orders

---

.github/workflows/deploy-production.yml

as discussed a protected infura key with special setup

 new infura key via secrets

---

src/constants/index.ts

Disable not supported wallets

---

src/components/auction/Claimer/index.tsx

Closes #347 
Just added an inline spinner as everywhere else. We'll have a better solution when we fix #296

(fix) multiple messages shown

---

src/pages/Licenses/index.tsx

(fix) licenses section typos

---

src/components/auction/AuctionDetails/index.tsx

I think in the other PR is was deleted by accident.

inserting the logo again

---

src/components/auction/Charts/XYChart.ts

Closes #443 
Look like this ..

0.0.. is shown with million

---

src/components/auction/AuctionDetails/index.tsx

Price should be quoteToken per baseToken, i.e. 2000 DAI per WETH

Correct price in auction details

---

src/state/transactions/hooks.tsx

All tx from the user are logged and also the ones that can be returning that an approval tx is pending, more than one could be an error (I'm not taking into account the timestamp in the log just to have more data available)
An extra hypothesis is that the tx, in some cases, doesn't have the `receipt` updated after being mined. This could be checking having the hash of the tx mined as seen in metamask and the last logged one.
A look into `Updater` function and seems solid, more details about the user flow before getting into this error would be very valuable as @mariano-aguero said.
The only thing left to say is that when I had this error in rinkeby, and had some extra logging, these logs appear a lot of times (thousands in a few minutes) like something running more than once (When it …

Log extra data for stuck approval

---

src/components/modals/common/CancelModalFooter/index.tsx

(change) Order canceling warning text

---

src/components/layout/Footer/index.tsx
src/components/modals/WalletModal/index.tsx

different forum link

---

src/docs/files/devguide01.md

There was a mistake in the md file that didnt allow one sentence to be correctly bolded.

Update devguide01.md 

---

.github/workflows/deploy-production-with-staging-api.yml

This PR enables to build a production setup but with the develop apis

Production setup with develop api

---

src/components/auction/AuctionDetails/index.tsx
src/components/auction/OrderbookChart/index.tsx
src/components/auction/OrderbookWidget/index.tsx
src/components/layout/Footer/index.tsx
src/components/navigation/Routes/Routes.tsx

Closes #464 
Closes #477
All right, someone lent me an iPhone 8 (the closest I could get to an iPhone 12, sorry) and I fixed several things. I could actually reproduce the same problems that were reported on other iOS devices, so I think the fixes here will work there too.
These screenshots are from the iPhone 8 I used:
Android, desktop, etc. should be the same as it was before.

(fix) iOS fixes

---

src/api/index.tsx
src/hooks/useClaimOrderCallback.ts

closes #440
@jarcodallo This was the solution I had in mind. Could you test whether its working as well?

different solution to 440

---

src/components/auction/AuctionDetails/index.tsx
src/components/auction/Charts/XYChart.ts
src/components/auction/OrderPlacement/index.tsx
src/components/auction/OrderbookWidget/index.tsx
src/components/auction/OrdersTable/index.tsx
src/components/form/FormLabel/index.tsx
src/components/form/PriceInputPanel/index.tsx
src/components/modals/common/PlaceOrderModalFooter/index.tsx
src/components/swap/styleds.ts
src/constants/config.ts
src/hooks/useChart.ts
src/hooks/usePlaceOrderCallback.ts
src/state/orderPlacement/actions.ts
src/state/orderPlacement/hooks.ts
src/state/orderPlacement/reducer.ts
src/utils/prices.ts

Just a draft: 
Tries to improve the situation for yfi sale.
Unfortunately, I could not improve the chart, because then we would get performance problems. Chart is too slow

frist step to inverted prices

---

src/components/modals/WalletModal/index.tsx
src/components/modals/common/PendingView/index.tsx
src/connectors/index.ts
src/hooks/index.ts

This solution should work for all wallets... with some small issues mentioned in the code

updated solution to work with m. wallet

---

package.json
src/components/modals/WalletModal/index.tsx
src/components/modals/common/PendingView/index.tsx
src/connectors/index.ts
src/hooks/index.ts
yarn.lock

Closes #355 
For this to work we need that NoahZinsmeister/web3-react#185 be merged or we could fork the subpackage of anxolin fork and use as a dependency (`web3-react/walletconnect-connector`)

Use all rpc independently of CHAIN_ID

---

src/hooks/useApproveCallback.ts
src/hooks/useCancelOrderCallback.ts
src/hooks/useClaimOrderCallback.ts
src/hooks/useGasPrice.ts
src/hooks/usePlaceOrderCallback.ts

Not sure how the approval blunder could happen.
useGas just got a performance improvement

fixes before customer test

---

src/components/auction/Claimer/index.tsx
src/components/auction/OrderPlacement/index.tsx
src/hooks/Tokens.ts
src/hooks/useAuctionDetails.ts
src/hooks/useClaimOrderCallback.ts
src/state/orderPlacement/hooks.ts

Orders section is not loaded when open an ended auction by a not conencted user

---

src/components/modals/WalletModal/index.tsx

(fix) 'Install Metamask' button

---

src/pages/Auction/index.tsx

tiny fix for inverted prices

---

src/components/auction/OrderPlacement/index.tsx
src/components/auction/Orderbook/index.tsx

`CurrencyInputPanel` was rendering multiple times because onMax was changing on each render. Also processData for orderBook is memorized, but it would be better to or denounce it, or make it faster (see #515).

Memoize function prop and order book data

---

src/docs/files/devguide01.md
src/docs/files/devguide02.md
src/docs/files/devguide03.md
src/docs/files/devguide04.md
src/docs/files/devguide05.md
src/docs/files/devguide06.md

Puh the quality of our docs is not optimal. This is just a quick prove reading from my side and I found many small issues.
We need to improve it quite a bit!
@Rafanator @avsavsavs Could you also go through it one more time ?

Docs improvements

---

src/components/auction/Charts/XYChart.ts

Adapting the chart legend. Please double check that it makes sense

Adapting the chart legend

---

src/components/auction/AuctionDetails/index.tsx
src/components/auction/OrderPlacement/index.tsx
src/components/auction/OrdersTable/index.tsx
src/components/layout/Header/index.tsx
src/components/modals/WalletModal/index.tsx
src/components/modals/common/PendingView/index.tsx
src/components/web3/Web3Status/index.tsx
src/hooks/index.ts
src/hooks/usePlaceOrderCallback.ts
src/state/index.ts
src/state/orderPlacement/hooks.ts
src/state/orderPlacement/reducer.test.ts
src/state/orderPlacement/reducer.ts

Simple renaming for better readabilty

rename swap -> orderplacement

---

src/components/auction/AuctionBody/index.tsx
src/components/auction/AuctionDetails/index.tsx
src/components/auction/AuctionTimer/index.tsx
src/components/auction/OrderPlacement/index.tsx
src/components/auction/OrdersTable/index.tsx
src/pages/Auction/index.tsx

removing unnecessary auctionState from interfaces of components

auction state handover

---

src/api/TokenLogosServiceApi.ts

If eth.link was not available, then the 1inch.eth.link token list was not able to load and hence, we would not even be able to load the page at all... not even in a non-ipfs hosted version.
Hopefully, this fixes the problem, such that https://ido-ux.dev.gnosisdev.com/#/start always loads

Still work page, even when some token symbols are not available

---

src/components/common/UserDropdown/index.tsx

Use close if is available

---

src/components/auction/Orderbook/index.tsx
src/components/auction/OrderbookChart/index.tsx

(fix) Chart height changing

---

src/state/orderPlacement/hooks.ts

closes: #541 
- Problem: 
The [`auctionState`](https://github.com/gnosis/ido-ux/blob/349dceb3a97b82a05901e1a219f013c3a1a5f725/src/state/orderPlacement/hooks.ts#L407) is not updated when auction `endTime` expires.
Added a `useEffect` that updates the `auctionState` when the **endTime** expires
- Enviroment
**auctionId:** 19, 20, 33
**chainId:** 4

Add set AuctionState after end time

---

src/components/auction/Charts/XYChart.ts

Use am4charts number formatter for tooltips

---

src/docs/files/devguide01.md
src/docs/files/devguide02.md
src/docs/files/devguide03.md
src/docs/files/devguide04.md
src/docs/files/devguide09.md
src/docs/files/devguide10.md

I like it much better if it gives a very high-level overview. Personally, in the old version, I would have stopped reading already once the auctioneer parameters are mentioned. They simply do not fit into the user flow for most users

docs: rewriting ### Gnosis Auction User flow

---

src/state/orderPlacement/hooks.ts
src/types.d.ts
src/utils/index.ts

Currently develop is no longer working, because in develop `isTimeout` was not defined

[fix]remove function declaration from types.d.ts file

---

src/components/layout/Footer/index.tsx

Closes #556 
@josojo Discord link seems to be invalid.

(add) support link

---

.eslintrc.js

Fix end of line eslint error on Windows

---

package.json
src/components/auction/AuctionDetails/index.tsx
src/components/auction/ExtraDetailsItem/index.tsx
src/components/auction/OrderbookTable/index.tsx
src/components/auction/OrdersTable/index.tsx
src/components/common/Tooltip/index.tsx
src/components/form/PriceInputPanel/index.tsx
src/components/layout/Header/index.tsx
src/components/navigation/Routes/Routes.tsx
src/pages/Overview/index.tsx
yarn.lock

Closes #576 
This should fix all the problems with the tooltips' z-index.
@maria-vslvn last PR added some new tooltips and I fixed those too, so I'm merging this PR into the branch she created to avoid having to fix more tooltips later.

(Fix) Tooltips z-index

---

src/components/auction/OrderPlacement/index.tsx

closes: #595 
Problem:
Confusing message and unused lines of code
**Enviroment**
auctionId: 19, 20
chainId: 4

Clarify the message, code cleanup

---

src/components/auction/Claimer/index.tsx
src/hooks/useClaimOrderCallback.ts
src/state/orderPlacement/hooks.ts

closes: #577 
Avoid another RPC call about from claim info, used in `useDerivedClaimInfo`
**Enviroment**:
auctionId: 90
chainId: 4

Add useGetClaimState

---

src/api/AdditionalServicesApi.ts

closes #648 
just saw this oneliner and hence made it quickly

Always request 4 most interesting auctions and not 3

---

src/components/auction/OrderPlacement/index.tsx

[easy] use biddingTokenDisplay in missing approval message

---

src/components/auction/AuctionDetails/index.tsx

[easy] minimum funding

---

src/components/layout/Footer/index.tsx

[easy] updating discord link

---

src/components/auction/OrderPlacement/index.tsx
src/components/auction/Orderbook/index.tsx
src/components/auction/OrdersTable/index.tsx
src/components/modals/common/PlaceOrderModalFooter/index.tsx
src/hooks/usePlaceOrderCallback.ts
src/state/orderPlacement/hooks.ts
src/state/orderPlacement/reducer.ts
src/utils/prices.ts

Making getInverse aware of null state -

---

src/components/auction/Claimer/index.tsx
src/components/pureStyledComponents/Error.tsx
src/state/orderPlacement/hooks.ts

Closes: #542 
error markup was moved to the claim btn title, and the if statement was extended with it. error styles were extended to fit buttons on mobile devices

auction pending settlement state moved on claim btn

---

src/pages/Terms/index.tsx

Updates from the legal team.
Could someone please review it quickly, and then we push it also in the release for tomorrow. thx

Updating to newest terms and conditions

---

src/components/auction/Claimer/index.tsx
src/components/auction/OrderPlacement/index.tsx
src/components/form/AmountInputPanel/index.tsx
src/hooks/useApproveCallback.ts
src/hooks/usePlaceOrderCallback.ts
src/state/orderPlacement/hooks.ts
src/state/wallet/hooks.ts
src/utils/index.ts

Closes #636, #660 
Still need to test this. I guess `isTokenWETH` must be improved to works for rinkeby too. 
Also I think I should do something like `useTokenBalancesTreatWETHAsETHonXDAI`.

Use native eth in order placement

---

src/components/form/PriceInputPanel/index.tsx

Get token display in price input panel

---

.github/workflows/deploy-production-with-staging-api.yml
.github/workflows/deploy-staging.yml
.github/workflows/deploy.yml

Just for us to make it more accessible

Renaming deployments

---

src/components/auction/AuctionDetails/index.tsx

Avoid running effect again when price is changed manually

---

src/constants/tokens/mainnet.ts

Add VITA mainnet token

---

src/components/auction/Orderbook/index.tsx
src/components/auction/OrderbookChart/index.tsx
src/components/auction/OrderbookTable/index.tsx

Fix order book list container layout

---

src/components/auctions/AuctionInfoCard/index.tsx
src/utils/numeral.ts

fixing price display in feature auction card

---

src/docs/files/devguide07.md

removing weth section from docs

---

src/api/AdditionalServicesApi.ts
src/components/auctions/HighestVolumeAuctions/index.tsx
src/hooks/useAllAuctionInfos.ts
src/hooks/useInterestingAuctionDetails.ts
src/pages/Landing/index.tsx

Highest volume auctions integration

---

src/components/auction/OrderbookTable/helpers.ts

Fix orderbook table percentage bigger than 100

---

src/utils/prices.ts

Prevent division by 0 when inverting prices

---

src/components/auction/AuctionDetails/index.tsx

Fix filling in min funding

---

src/components/buttons/ButtonConnect/index.tsx
src/components/buttons/buttonStylingTypes.ts
src/components/common/UserDropdown/index.tsx
src/components/pureStyledComponents/FieldRow.tsx

Add font-family missing

---

src/api/TokenLogosServiceApi.ts

Adding the tokenlist from kleros and coingecko. Though coingecko resolution is quite bad and we should not rely on it.

New tokenlist for token curation

---

src/components/auction/AuctionBody/index.tsx
src/components/auction/AuctionTimer/index.tsx
src/state/orderPlacement/hooks.ts

Add new settlement state to auction details

---

src/components/auction/AuctionDetails/index.tsx
src/components/auctions/HighestVolumeAuctions/index.tsx
src/hooks/useAllAuctionInfos.ts

Once the backend is updated to the latest code, this should fix the issues seen on ido-ux deployment.

Updates to deal with the new backend logic

---

src/components/auction/Claimer/index.tsx

Fix claiming on unsupported network

---

src/components/auction/Charts/XYChart.ts
src/components/auction/OrderbookChart/index.tsx
src/hooks/useChart.ts

closes #769
The legend of current price displayed a mock price data.
This implementation uses PR #629 as a base.

Display the current price in legend

---

src/state/application/updater.ts

closes: #765
When the `chainId` is changed, the `blockNumber` is writing to the erroneous key (`chainId`) in `application` reducer state.

Avoid write blockNumber in erroneous chainId

---

src/components/form/AmountInputPanel/index.tsx

position for unwrap element

---

src/components/popups/TxnPopup/index.tsx

tooltip content fix

---

src/components/auction/Claimer/index.tsx
src/components/modals/common/Option/index.tsx
src/theme/index.tsx
src/theme/styled.d.ts

-few more theming issues fixes (options: hover, double field bg)
before update:
after update:

theming issues fix

---

package.json
src/components/layout/Footer/index.tsx
yarn.lock

Adds additional link for dune dashboards

Adding dune dashboard for analystics

---

src/constants/index.ts

fixes https://github.com/gnosis/ido-ux/issues/820 and https://github.com/gnosis/ido-ux/issues/822

Add polygon to chainNames
